import "./globals.css";
import { Montserrat } from "next/font/google";

const montserat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserat.className} sm:mx-8 md:mx-24`}>
        {children}
      </body>
    </html>
  );
}
